varsion: 0.1
phase:
  install:
    commands:
      -npm install time
      -aws cloudformation pachage --template-file samTemplate.yaml --s3-bucket lambda-functin-src-20170620 --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
    
