version: 0.2
phases:
  install:
    commands:
    - npm install time
    - aws cloudformation package --template-file samTemplate.yaml --output-template-file NewSamTemplate.yaml --s3-bucket lambda-function-src-20170620
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
